version: '3'
services:
  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    volumes:
      - $PWD/data:/data
      - /var/log:/var/log:ro
    env_file:
      - $PWD/fail2ban.env

networks:
  host:
    external: true
