version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
        #- "80:80/tcp"
        #- "443:443/tcp"
      - "8053:80/tcp"
    environment:
      TZ: 'Asia/Seoul'
      WEBPASSWORD: '3mkm300p'
      ServerIP: 192.168.0.25
      PROXY_LOCATION: pihole
      VIRTUALHOST: pihole.luel.duckdns.org
      VIRTUAL_PORT: 8081
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:pihole.luel.duckdns,{catchall:.*}"
      - "traefik.frontend.priority=1"
      - "traefik.backend=pihole"
      - "traefik.port=80"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
