defaultEntryPoints = ["http"]
[entryPoints]
    [entryPoints.web]
    address = ":80"

    [entryPoints.websecure]
    address = ":443"

[log]
    level = "DEBUG"

[api]
    insecure = true
    
[docker]
    endpoint = "unix://var/run/docker.sock"
    domain = "docker.localhost"
    exposedByDefault = false

[acme]
entryPoint = "https"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
onHostRule = true
    [acme.httpChallenge]
        entryPoint = "http"
    [acme.dnsChallenge]
        provider = "cloudflare"
        delayBeforeCheck = 0
    [[acme.domains]]
    main = "*.docker.localhost"
