version: '2'

services:
  proxy:
    image: traefik:alpine
    command: --web --docker --docker.domain=luel.duckdns.org --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - webgateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      
  whoami:
    image: containous/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:luel.duckdns.org"
    networks:
      - web

networks:
  webgateway:
    driver: bridge
  web:
    external:
      name: v12_webgateway

