version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/data:/data
  caddy:
    image: caddy/caddy
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - portainer
